export const REVIEWABLE_REQUESTS_CREATOR = "REVIEWABLE_REQUESTS_CREATOR";
export const TOKEN_FACTORY_EXECUTOR = "TOKEN_FACTORY_EXECUTOR";

export const REVIEWABLE_REQUESTS_RESOURCE = "REVIEWABLE_REQUESTS_RESOURCE";
export const TOKEN_REGISTRY_RESOURCE = "TOKEN_REGISTRY_RESOURCE";
export const TOKEN_FACTORY_RESOURCE = "TOKEN_FACTORY_RESOURCE";

export const CREATE_PERMISSION = "CREATE";
export const EXECUTE_PERMISSION = "EXECUTE";

export const TOKEN_REGISTRY_DEP = "TOKEN_REGISTRY";
export const TOKEN_FACTORY_DEP = "TOKEN_FACTORY";

export const confMap = {
  MasterContractsRegistry: "",
};
